name: Push image to dockerhub

on: 
  workflow_call:
    inputs:
      GITHUB_AGENT:
        type: string
        required: false
        default: "ubuntu-latest"
      DOCKER_IMAGE_NAME: 
        type: string
        required: true
      DOCKER_IMAGE_TAG: 
        type: string
        required: true
      DOCKER_IMAGE_VERSION:
        type: string
        required: true
      DOCKER_IMAGE_PATH:
        type: string
        required: true
    outputs:
      out_status:
        description: "Status of pushing the image"
        value: ${{ jobs.docker-build-push.outputs.output1 }}
    secrets:
      DOCKER_HUB_USER:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true


jobs:
  docker-build-push:
    runs-on: ${{ inputs.GITHUB_AGENT }}
    outputs:
      output1: ${{ steps.final_step.outputs.out_result }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image for bot App
        run: docker build -f ${{ inputs.DOCKER_IMAGE_PATH }} --tag ${{ secrets.DOCKER_HUB_USER }}/${{ inputs.DOCKER_IMAGE_NAME }}:${{ inputs.DOCKER_IMAGE_TAG }} --tag ${{ secrets.DOCKER_HUB_USER }}/${{ inputs.DOCKER_IMAGE_NAME }}:${{ inputs.DOCKER_IMAGE_VERSION }} .

      - name: Push the image w/ tags
        run: docker push -a ${{ secrets.DOCKER_HUB_USER }}/${{ inputs.DOCKER_IMAGE_NAME }}:${{ inputs.DOCKER_IMAGE_TAG }}

      - id: final_step
        if: success()
        run: echo "out_result=success" >> $GITHUB_OUTPUT